'use client';
import QRCode from 'qrcode';
import {useEffect,useState} from 'react';

function sortTables(a,b){const ap=a.name.match(/^([A-Z]+)(\d+)$/i),bp=b.name.match(/^([A-Z]+)(\d+)$/i);if(ap&&bp){const c=ap[1].localeCompare(bp[1]);return c||Number(ap[2])-Number(bp[2]);}return a.name.localeCompare(b.name);}

export default function QRPage(){
  const[rows,setRows]=useState([]);const[err,setErr]=useState('');
  useEffect(()=>{(async()=>{const r=await fetch('/api/manager/dashboard',{cache:'no-store'});const j=await r.json();if(!r.ok){setErr(j.error||'Manager login required.');return}const base=window.location.origin;const out=[];for(const t of (j.tables||[]).filter(x=>x.active).sort(sortTables)){const url=`${base}/t/${t.token}`;out.push({...t,url,qr:await QRCode.toDataURL(url,{width:600,margin:1,errorCorrectionLevel:'H'})})}setRows(out)})()},[]);
  return <><style jsx global>{`
    .qr-print-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:20px;margin-top:18px}.qr-label{width:200px;height:200px;border-radius:50%;box-sizing:border-box;margin:auto;background:#fff;border:2px solid #d7ab58;display:flex;flex-direction:column;align-items:center;justify-content:center;overflow:hidden;padding:12px;text-align:center}.qr-brand{font-weight:900;font-size:16px;line-height:1;letter-spacing:1px;color:#241c18}.qr-sub{font-size:7px;letter-spacing:1.7px;color:#ad1d22;font-weight:800;margin-top:3px}.qr-code{width:112px;height:112px;display:block;margin:3px auto 1px}.qr-table{font-size:24px;line-height:1;font-weight:900;color:#ad1d22}.qr-hint{font-size:7px;line-height:1;margin-top:3px;color:#665b54;letter-spacing:.7px}.qr-screen-actions{text-align:center;margin-top:8px}
    @media print{@page{margin:5mm}.topbar,.qr-screen-actions,.no-print{display:none!important}body{background:#fff!important}.page{max-width:none!important;margin:0!important;padding:0!important}.qr-print-grid{display:grid!important;grid-template-columns:repeat(3,50mm)!important;gap:4mm!important;justify-content:center!important;margin:0!important}.qr-label{width:50mm!important;height:50mm!important;min-width:50mm!important;min-height:50mm!important;border-radius:50%!important;border:.45mm solid #d7ab58!important;padding:2.5mm!important;break-inside:avoid!important;page-break-inside:avoid!important}.qr-brand{font-size:4mm!important}.qr-sub{font-size:1.7mm!important;margin-top:.7mm!important}.qr-code{width:28mm!important;height:28mm!important;margin:.5mm auto 0!important}.qr-table{font-size:6mm!important}.qr-hint{font-size:1.6mm!important;margin-top:.5mm!important}}
  `}</style><div className="topbar"><div className="logo">MEAT HOUSE<small>TABLE QR CODES</small></div><span className="spacer"/><a className="btn secondary small" href="/manager">Manager</a><button className="btn gold small" onClick={()=>window.print()}>PRINT 50MM LABELS</button></div><main className="page">{err&&<div className="error">{err}</div>}<div className="notice no-print">Print layout: 50mm circular labels · Meat House · QR code · table number. Set browser print scale to 100% / Actual size.</div><div className="qr-print-grid">{rows.map(t=><div key={t.id}><div className="qr-label"><div className="qr-brand">MEAT HOUSE</div><div className="qr-sub">CHINESE BBQ BUFFET</div><img className="qr-code" src={t.qr} alt={`${t.name} QR`}/><div className="qr-table">{t.name}</div><div className="qr-hint">SCAN TO ORDER</div></div><div className="qr-screen-actions no-print"><a className="btn secondary small" href={t.qr} download={`MeatHouse-${t.name}.png`}>QR PNG</a></div></div>)}</div></main></>;
}
