'use client';
import QRCode from 'qrcode';
import {useEffect,useState} from 'react';

const LOGO='data:image/webp;base64,UklGRuR/AAA...';

function sortTables(a,b){const ap=a.name.match(/^([A-Z]+)(\d+)$/i),bp=b.name.match(/^([A-Z]+)(\d+)$/i);if(ap&&bp){const c=ap[1].localeCompare(bp[1]);return c||Number(ap[2])-Number(bp[2]);}return a.name.localeCompare(b.name);}

export default function QRPage(){
  const[rows,setRows]=useState([]);const[err,setErr]=useState('');
  useEffect(()=>{(async()=>{const r=await fetch('/api/manager/dashboard',{cache:'no-store'});const j=await r.json();if(!r.ok){setErr(j.error||'Manager login required.');return}const base=window.location.origin;const out=[];for(const t of (j.tables||[]).filter(x=>x.active).sort(sortTables)){const url=`${base}/t/${t.token}`;out.push({...t,url,qr:await QRCode.toDataURL(url,{width:700,margin:1,errorCorrectionLevel:'H',color:{dark:'#000000',light:'#ffffff'}})})}setRows(out)})()},[]);

  return <><style jsx global>{`
    .qr-print-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:26px;margin-top:20px}.qr-wrap{text-align:center}.qr-label{position:relative;width:220px;height:220px;border-radius:50%;box-sizing:border-box;margin:auto;background:#0c0c0c;overflow:hidden;box-shadow:0 0 0 7px #090909}.qr-label:after{content:'';position:absolute;inset:9px;border:3px solid #d61f2b;border-radius:50%;pointer-events:none}.qr-logo-img{position:absolute;z-index:2;top:13px;left:50%;transform:translateX(-50%);width:94px;height:58px;object-fit:contain}.qr-whitebox{position:absolute;z-index:2;left:50%;top:70px;transform:translateX(-50%);width:112px;height:112px;background:#fff;border-radius:12px;padding:7px;display:grid;place-items:center;box-sizing:border-box}.qr-code{width:98px;height:98px;display:block}.qr-tableline{position:absolute;z-index:2;left:0;right:0;top:184px;height:25px;display:flex;align-items:center;justify-content:center;gap:7px;color:#fff;font-weight:900;line-height:1}.qr-tableword{font-size:14px;letter-spacing:.5px}.qr-tableno{font-size:27px;color:#e0252e}.qr-hint{position:absolute;z-index:2;left:0;right:0;top:207px;color:#fff;font-size:8px;letter-spacing:1.1px;font-weight:700}.qr-screen-actions{margin-top:13px}.qr-note{margin-top:12px}
    @media print{@page{margin:5mm}.topbar,.qr-screen-actions,.no-print{display:none!important}body{background:#fff!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}.page{max-width:none!important;margin:0!important;padding:0!important}.qr-print-grid{display:grid!important;grid-template-columns:repeat(3,50mm)!important;gap:4mm!important;justify-content:center!important;margin:0!important}.qr-wrap{width:50mm!important;height:50mm!important;break-inside:avoid!important;page-break-inside:avoid!important}.qr-label{width:50mm!important;height:50mm!important;box-shadow:0 0 0 1.5mm #090909!important}.qr-label:after{inset:2.1mm!important;border-width:.65mm!important}.qr-logo-img{top:3mm!important;width:21.5mm!important;height:13mm!important}.qr-whitebox{top:16mm!important;width:25.5mm!important;height:25.5mm!important;border-radius:2.5mm!important;padding:1.5mm!important}.qr-code{width:22.5mm!important;height:22.5mm!important}.qr-tableline{top:41.5mm!important;height:5.6mm!important;gap:1.4mm!important}.qr-tableword{font-size:3.1mm!important}.qr-tableno{font-size:6.2mm!important}.qr-hint{top:47mm!important;font-size:1.7mm!important;letter-spacing:.25mm!important}}
  `}</style>
  <div className="topbar"><div className="logo">MEAT HOUSE<small>TABLE QR CODES</small></div><span className="spacer"/><a className="btn secondary small" href="/manager">Manager</a><button className="btn gold small" onClick={()=>window.print()}>PRINT 50MM LABELS</button></div>
  <main className="page">{err&&<div className="error">{err}</div>}<div className="notice no-print qr-note">Approved 50mm black circular template. Print at 100% / Actual size and enable Background graphics.</div><div className="qr-print-grid">{rows.map(t=><div className="qr-wrap" key={t.id}><div className="qr-label"><img src={LOGO} className="qr-logo-img" alt="Meat House"/><div className="qr-whitebox"><img className="qr-code" src={t.qr} alt={`${t.name} QR`}/></div><div className="qr-tableline"><span className="qr-tableword">TABLE</span><span className="qr-tableno">{t.name}</span></div><div className="qr-hint">SCAN TO ORDER</div></div><div className="qr-screen-actions no-print"><a className="btn secondary small" href={t.qr} download={`MeatHouse-${t.name}-QR.png`}>QR PNG</a></div></div>)}</div></main></>;
}
